[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
solc = '0.8.24'

remappings = [
    '@chainlink/contracts-ccip=lib/ccip/contracts',
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@chainlink/local/=lib/chainlink-local/',
]

[rpc_endpoints]
sepolia-local = "http://127.0.0.1:8545"
ronin-local = "http://127.0.0.1:8546"
sepolia = "${SEPOLIA_PRIVATE_RPC}"
ronin-testnet = "${SAIGON_PRIVATE_RPC}"

[fmt]
line_length = 120

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
